CS599-MEDLINE/pubminer-web-app

README.md, docker-compose.yml, docker/postgres/pubminer-schema.sql
Adds support for running `postgres` locally (resolved #2).
=> Docker postgres

app.js, package.json, routes/detail.js, search.js
This is still pretty rough, but I figured I'd PR it since pretty much everything is rough right now. I temporarily commented out the MySQL stuff just because it was logging quite a bit. We can turn it back on once we have some stuff that uses it.
=> Result detail api

docker-compose.yml, search.js
change the detail result to contain fields for each abstract type
=> minor cleanup of detail API

search.js
Handles some additional document formats and gives better error messages.
=> Improve handling of unexpected document formats

less/pmstyles.less, views/layout.pug, views/resultRow.pug
Need to run gulp on local system to rebuild combined css after this change.
=> Trim author list and add loading indicator

package.json, search.js, services/PubMedService.js
This is WIP to pull all PubMed API calls into its own service. This code isn't used yet, so there is no urgency to merge it.
=> WIP - PubMed service refactoring

README.md, cypress.json, cypress/fixtures/example.json, cypress/fixtures/profile.json, cypress/fixtures/users.json, cypress/integration/example_spec.js, cypress/integration/search_spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, package-lock.json, package.json, services/PubMedService.js
This adds basic integration testing support using Cyprus and one example test. More detailed tests to follow...
=> Integration Test with Cyprus

.gitignore, config/default.json, package-lock.json, package.json, search.js, services/PubMedService.js, test/ConfigurationSpec.js, test/PubMedServiceSpec.js, test/data/search/pubmed_search_success.json
This change adds the first couple of unit tests using `mocha`.
=> Add unit tests using mocha

app.js, package-lock.json, package.json, public/images/PubMinerLogo.svg, public/images/PubMinerText.svg, public/scripts/pubminer.js, routes/results.js, views/layout.pug, views/list.pug, views/resultRow.pug, views/results.pug
Includes revisions to masthead and javascript code to support passing checked items to the back end.
=> UI support for Export feature

db.js, package-lock.json, search.js, services/DemographicsService.js, services/PubMedService.js, test/PubMedServiceSpec.js, test/data/summary/pubmed-esummary-success.json
I've stubbed out the calls to Postgres for now since we are expecting to replace it shortly. Refactored the `fetchSummary` part of the `PubMedService` and added a unit test to verify the call to NCBI `esummary` is constructed correctly.
There are still some minor inconsistencies in the code that I will aim to clean up in the new couple of pull requests
=> refactor fetchSummary and add unit test

package-lock.json, package.json, search.js, services/DemographicsService.js
Items that we don't pull in from dynamo are dropped for now
=> add dynamodb wiring

services/DemographicsService.js
Resolves the issue reported in #45
=> Fix call to batchGet with empty set of keys

services/DemographicsService.js
- remove verbose logging
- remove unneeded call to `filter`
- log warning message for empty ID set
=> minor cleanup in DemographicsService

services/DemographicsService.js
This pull table1 from `DynamoDB` into a table1 result for the UI
=> pull table1 into search results

.travis.yml
This should automatically run unit tests for pull requests or pushes
=> add basic travis config

less/pmstyles.less, search.js, views/accordionTable1.pug, views/resultRowExpansion.pug
Minor changes to formatting, including making table 1 100% of accordion width
=> Formatting changes (table 1 width = 100%)

public/scripts/pubminer.js, views/list.pug, views/results.pug
This check-in corrects issue #79, where our code was attempting to initialize a result's table 1 section.
Also includes a very minor fix to format quotations using html entities.
=> Fix DataTable issue (#79)

DocumentHelper.js, Errors.js, config/default.json, routes/results.js, search.js, services/PubMedService.js, test/ConfigurationSpec.js, test/DocumentHelperSpec.js, test/PubMedServiceSpec.js, test/QueryHelperSpec.js, test/data/detail/efetch.xml, views/results.pug
Introduces a basic error handling approach. Some of this code is still messy, but it should resolve #57 at a minimum. This change also introduces some more refactoring and tests.
=> Error Handling

DocumentHelper.js, services/DemographicsService.js
This change limits the information retained in the summary responses to just what is needed by the UI
=> clean up the Summary response

DocumentHelper.js, routes/detail.js, test/DocumentHelperSpec.js
PMID/PMCID needs to be included from the summary results rather than the demographic results since we won't necessarily have a demographic result for every search result
=> Fix pmid pmcid

public/scripts/pubminer.js
=> Add search term to exported CSV.

DocumentHelper.js, services/DemographicsService.js, test/DocumentHelperSpec.js
Groups sentences in a section by concatenating them using a space. We should evaluate displaying these as an unordered list in the UI or something.
=> group sentences by section

DocumentHelper.js, Errors.js, config/default.json, routes/list.js, search.js, services/DemographicsService.js, services/PubMedService.js, test/ConfigurationSpec.js, test/DocumentHelperSpec.js, test/PubMedServiceSpec.js, test/data/search/pubmed_search_too_many_results.json, test/data/search/pubmed_search_zero_results.json
Email info in the last commits was incorrect and this fixes the commit metadata
=> Fix commits

config/default.json, services/PubMedService.js
The error messages for service timeouts isn't the best right now. I will have a follow-up PR that improves error handling holistically.
=> add sensible timeouts for NCBI service calls

views/about.pug, views/navBar.pug
About popup with version information and a link to the NCBI copyright notice.
=> Add an About popup.

cypress/integration/home_spec.js, views/list.pug
Fixes the home_spec group of tests.
=> Fixes for Cypress tests.

README.md
=> Fixing Mocha test command.

.jshintrc, DocumentHelper.js, QueryHelper.js, app.js, cypress/plugins/index.js, cypress/support/commands.js, gulpfile.js, package.json, routes/detail.js, routes/list.js, routes/results.js, search.js, services/DemographicsService.js, test/ConfigurationSpec.js, test/DemographicServiceSpec.js, test/DocumentHelperSpec.js, test/PubMedServiceSpec.js, test/QueryHelperSpec.js
Fixes linting errors across the project. Only the Cypress directory is excluded for now
=> Apply linting to whole project

.travis.yml, package-lock.json, package.json, test/DemographicServiceSpec.js
I think a better approach would probably be to try using an embedded instance of DynamoDb, but this is quick and does provide some converage in the limited time we have left. This approach is probably acceptable given the limited number of test cases we need to exercise.
=> example test of DemographicService

README.md
show coverage and build status in README.md
=> add coverage and build status badges

.gitignore, DocumentHelper.js, Errors.js, package.json, test/DocumentHelperSpec.js, test/QueryHelperSpec.js, test/data/demographics/fake_demo_data.json
Adds unit tests to improve coverage. Also adds the `coverage` directory to `.gitignore` and excludes that directory from linting.
=> Improve coverage
